### ISSUE TITLE
regex_expression for coverage report

### ISSUE THREAD

**Issue by rafael-trevisan** [utPLSQL/utPLSQL-cli#104]
Hi guys,

I'm struggling to set regex_expression to run a coverage report in my folder structure.

What I have is:
```
+--project_a
+----src
+------functions
|--------func1.sql
|--------func2.sql
+------procedures
|--------proc1.sql
|--------proc2.sql
+----test
+------functions
|--------func1.sql
|--------func2.sql
+------procedures
|--------proc1.sql
|--------proc2.sql
```

And what I'm trying is:
```
-p=my_schema,
-source_path=src,
-regex_expression="/(\w+)/(\w+)\..{3}$",
-type_mapping="procedures=PROCEDURE/functions=FUNCTION",
-name_subexpression=2,
-type_subexpression=1,
-test_path=test,
-regex_expression="/(\w+)/(\w+)\..{3}$",
-type_mapping="procedures=PROCEDURE/functions=FUNCTION",
-name_subexpression=2,
-type_subexpression=1,
-f=ut_coverage_html_reporter -o=coverage.html
```

I've read the https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/coverage.md#project-based-coverage but as I don't have the `owner` level in my structure I did some change to the regex. I've checked it here https://regex101.com/r/Vd97v0/1 and it seems to be a working regex.

Is there anything else am I missing?

**Comment by rafael-trevisan** [comment]
It's worth to say: if I run the coverage report against my database it works nicely :) but I wanted to run it against the source/test folder.

**Comment by rafael-trevisan** [comment]
Never mind guys... I was messing things up

**Comment by jgebal** [comment]
@rafael-trevisan 
Does it work for you now?

**Comment by rafael-trevisan** [comment]
Yeah, I hadn’t got the right concept. Is all good 👍🏻
