### ISSUE TITLE
utPLSQL-cli run is not working when NLS_LANG is set

### ISSUE THREAD

**Issue by nikita-mospan** [utPLSQL/utPLSQL-cli#109]
Good day!

I downloaded utPLSQL-cli v3.1.2 , added ojdbc8.jar and orai18n.jar from Oracle website to utPLSQL-cli/bin folder. However I still didn't manage to make utplsql run work when NLS_LANG is set. Please consider output below:

`$ echo $NLS_LANG`
AMERICAN_AMERICA.AL32UTF8

`$ ./utplsql run tech_user/1@ora12c`
jdbc:oracle:oci8:****/****@ora12c: no ocijdbc12 in java.library.path
jdbc:oracle:thin:****/****@ora12c: Locale not recognized
Could not establish connection to database. Reason: Locale not recognized

`$ unset NLS_LANG`

`$ ./utplsql run tech_user/1@ora12c`
Between string function
  Returns substring from start position to end position [,023 sec]
  Returns substring when start position is zero [,003 sec]

Test package for pk_util_log
  Check that entry is created in tech_log_instances table [,01 sec]
  g_log_entry_creation_actual: 902

Finished in ,040518 seconds
3 tests, 0 failed, 0 errored, 0 disabled, 0 warning(s)

So the error is a bit different from https://github.com/utPLSQL/utPLSQL-cli/issues/101 but still the problem seems to exist.

Thank you.

**Comment by pesse** [comment]
Hi @nikita-mospan 

the release provides the wrong download files. We are working on a fix.
The correct release-version can already be found here: https://bintray.com/utplsql/utPLSQL-cli/download_file?file_path=utPLSQL-cli-develop-201810230847.zip

Can you give it a try?

**Comment by nikita-mospan** [comment]
Hi @pesse 
Yes, zip from bintray works.

Thank you.

**Comment by pesse** [comment]
And now the correct binaries are available on the release-page.
