### ISSUE TITLE
Failing to execute

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-cli#11]
Downloaded latest develop version.
Executed: `utplsql.bat run user/pass@db` 
And got:
```
java.lang.NullPointerException
        at io.github.utplsql.cli.RunCommand.run(RunCommand.java:97)
        at io.github.utplsql.cli.Cli.main(Cli.java:23)
```
using Windows 7 and Java:
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by viniciusam** [comment]
Fixed the NullPointerException, but you will probably run on an Invalid connection string error. I need to work on a better support of different connection strings.

Please give it a try.
