### ISSUE TITLE
Calling utplsql.bat without parameters

### ISSUE THREAD

**Issue by alesana-san** [utPLSQL/utPLSQL-cli#110]
Hi!

I guess it would be handy if CLI returned some help stuff instead of "Unknown command: 'null'".
Now I get that line when I call just "utplsql.bat" in a command prompt.

my utplsql-cli version: 3.1.2.271

**Comment by jgebal** [comment]
Agree
Should provide a list of available commands like:
- run
- info
- reporters

**Comment by pesse** [comment]
I think it's a bug. Thanks for the finding.
