### ISSUE TITLE
Exclude or Include multiple packages

### ISSUE THREAD

**Issue by successshrestha** [utPLSQL/utPLSQL-cli#116]
I got multiple test packages in same schema(utplsql). Half of the packages test the individual tables and the rest compares the tables. I want to integrated it into bamboo and generate a report, How can i include or exclude multiple test packages. I tried using -p but it can only take upto 2 packages.

**test packages**
test_table1
test_table2
test_table3                   
test_table4
test_table5
test_table6

**test packages for table comparision**
test_comp_tbl1
test_comp_tbl2
test_comp_tbl3
test_comp_tbl4

Edit: i have defined suitepath(table_test) for the upper tables. but i am unable to run the packages. I tried using -p=utplsql:table_test . But that wont work.

**Comment by jgebal** [comment]
Is UTPLSQL the schema name that owns the `test_table1` suite?

**Comment by successshrestha** [comment]
Yes. There was a silly mistake in the connection url. Its been solved.
