### ISSUE TITLE
MD5 Hash

### ISSUE THREAD

**Issue by richard-j-smith** [utPLSQL/utPLSQL-cli#128]
Would it be possible to provide an MD5 hash has for the latest utPLSQL-clip.zip file as we work in a secured environment and we need to provide an MD5 hash to the security team to be able to upload software to the environment. We are currently using utPLSQL-cli-v1.0.0 and we are planning to upgrade both utPLSQL and this utPLSQL-cli to the latest versions.

Thanks

**Comment by pesse** [comment]
Hi @richard-j-smith,
MD5 for 3.1.2 is 
`2e1c7b1dffee1f407c20f9f033428d72`

We will add md5-files automatically for all future releases, thanks for pointing out.
