### ISSUE TITLE
Ability to enable/disable DBMS_OUTPUT from cli

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-cli#137]
Previous versions of `cli` had DBMS_OUTPUT.ENABLED;
With release `3.1.6` this is no longer the case.
Some of our tests are relying on DBMS_OUTPUT and were working properly on previous version of cli. They started failing after upgrade.

**Comment by jgebal** [comment]
Ideally that schold be parameter to cli.
This way user can have control over that behavior.
I woyld leave default enabled probably.

**Comment by jgebal** [comment]
Or follow sqlcl and sqlplus (default=disabled)

**Comment by pesse** [comment]
Love the idea of a parameter
