### ISSUE TITLE
How to use utplsql with -q?

### ISSUE THREAD

**Issue by kga676** [utPLSQL/utPLSQL-cli#138]
Please give me an exaple of of calling utplsql.bat with -q key
like ulplsql <connect options> -p=suite
I tried everything but still can not understand where i should put the "-q" key

**Comment by pesse** [comment]
```
utplsql.bat run user/password@host:port/service -q
```
or 
```
utplsql run user/password@host:port/service -q
```

**Comment by kga676** [comment]
And i got this
![image](https://user-images.githubusercontent.com/45682640/55166424-25010b80-5180-11e9-91f3-3b2545ac8bae.png)

**Comment by pesse** [comment]
This is strange.
Can you provide the output of `utplsql info` ?

**Comment by kga676** [comment]
Here it is
I installed cli by Ctrl+C -> Ctrl+V in my old cli folder
![image](https://user-images.githubusercontent.com/45682640/55173459-ce4dfe80-518c-11e9-98bd-afdf29ff6cf3.png)

**Comment by kga676** [comment]
Fixed that by clear installing. Thanks for run example

**Comment by pesse** [comment]
You're welcome!
