### ISSUE TITLE
CLI fails to map sources/tests with code

### ISSUE THREAD

**Issue by alesana-san** [utPLSQL/utPLSQL-cli#146]
Hi!

I post here full information about problem with running CLI using Jenkins CI.
I have the following folder structure:
`````
12:12:29 + pwd
12:12:29 /u01/jenkins_slave/workspace/EPS/simplePayment_update_db
12:12:30 + find . -type d
12:12:30 .
12:12:30 ./tests
12:12:30 ./tests/sp_delayed_requests
12:12:30 ./tests/sp_errors
12:12:30 ./tests/sp_transaction_data
12:12:30 ./tests/sp_transactions
12:12:30 ./tests/views
12:12:30 ./scripts
12:12:30 ./scripts/556376
12:12:30 ./lib
12:12:30 ./utplsql
12:12:30 ./compiled
12:12:30 ./compiled/specs
12:12:30 ./compiled/types
12:12:30 ./compiled/bodies
12:12:30 ./compiled/views
12:12:30 ./rollback
12:12:30 ./rollback/556376
12:12:30 ./changelogs 
`````
Here's my debug xml outputs: [debug_xmls.zip](https://github.com/utPLSQL/utPLSQL-cli/files/3135917/debug_xmls.zip)
The owner of tests/sources is the same user I use to connect to DB.
Adding some logging stuff inside `utplsql` mapping routings showed that CLI sends right amount of paths but they are all NULLs (meaning that for 23 `source` files I saw map array with 23 entries but all of them were NULL in PL/SQL).
Versions of `utplsql` and `utplsql-cli` were the latest at the end of April.

**Comment by pesse** [comment]
Hi @alesana-san ,
can you please try the following cli-version with debug-option on ( `-d` ) and provide the output (you can also send it to me in private)?

https://bintray.com/utplsql/utPLSQL-cli/download_file?file_path=utPLSQL-cli-develop-201905150804.zip

**Comment by alesana-san** [comment]
Finally found out that my CLI `lib` directory lacked `orai18n.jar`.
The probable problem is https://stackoverflow.com/questions/14998299/oracle-array-filled-with-null-data-in-java
