### ISSUE TITLE
HTML reporter not working

### ISSUE THREAD

**Issue by viniciusam** [utPLSQL/utPLSQL-cli#17]
The ut_coverage_html_reporter is not working, probably because the default constructor is not being called, so the assets path don't get the default value: `ut_coverage_report_html_helper.get_default_html_assets_path()`.

Need to find a way to work this ou or get the default constructors called on the database. This may affect other reporters.

**Comment by jgebal** [comment]
Maybe asktom could help?

**Comment by jgebal** [comment]
@viniciusam, can you review open issues and see which can be closed already?
