### ISSUE TITLE
Code Coverage : Unit Test and Coverage Schema different 

### ISSUE THREAD

**Issue by DrErique** [utPLSQL/utPLSQL-cli#174]
Hello and greetings from Hannover, Germany.
I have a question that affects the circumstance that our unit tests exists in a different schema than the tested code. The utPLSQL Framework invented the "a_coverage_schemes" - Parameter for that case.
For example 
exec ut.run('UNITTEST', ut_coverage_html_reporter(), a_coverage_schemes=>ut_varchar2_list('ISUSER'));
Is there a way to do the same call with utplsql-cli ?

**Comment by pesse** [comment]
Hey @DrErique ,
thanks for your patience and for pointing this out.
You are right - for some reason there is no cli parameter to pass `a_coverage_schemes` to the test-runner, although Java-API would allow it.
I'll add this, shouldn't be a big problem.

**Comment by DrErique** [comment]
Hello Samuel,

This would be a real help for us, because otherwise there is no implementation in Bamboo possible and I have to create the reports per hand.
What shouldn't be the sense of it all.

Please let me know if you got a beta version for us to try this out.

Kind regards,
Derik Wehrmann

_________________________________________________________________

Tel: -551 | Testmanager | IT SCM

Von: Samuel Nitsche <notifications@github.com>
Gesendet: Dienstag, 10. März 2020 22:40
An: utPLSQL/utPLSQL-cli <utPLSQL-cli@noreply.github.com>
Cc: Wehrmann, Derik <D.Wehrmann@wertgarantie.com>; Mention <mention@noreply.github.com>
Betreff: Re: [utPLSQL/utPLSQL-cli] Code Coverage : Unit Test and Coverage Schema different (#174)


Hey @DrErique<https://github.com/DrErique> ,
thanks for your patience and for pointing this out.
You are right - for some reason there is no cli parameter to pass a_coverage_schemes to the test-runner, although Java-API would allow it.
I'll add this, shouldn't be a big problem.

**Comment by pesse** [comment]
@DrErique can you try out this one?
https://bintray.com/utplsql/utPLSQL-cli/download_file?file_path=utPLSQL-cli-develop-202003131529.zip

Parameter is `--coverage-schemes`

**Comment by DrErique** [comment]
Hello Samuel,

Seems to work pretty stable.
I saw even the documentation is already added.

So thanks for replying an keep healthy !

With kind regards
Derik Wehrmann



Von: Samuel Nitsche <notifications@github.com>
Gesendet: Freitag, 13. März 2020 16:32
An: utPLSQL/utPLSQL-cli <utPLSQL-cli@noreply.github.com>
Cc: Wehrmann, Derik <D.Wehrmann@wertgarantie.com>; Mention <mention@noreply.github.com>
Betreff: Re: [utPLSQL/utPLSQL-cli] Code Coverage : Unit Test and Coverage Schema different (#174)


@DrErique<https://github.com/DrErique> can you try out this one?
https://bintray.com/utplsql/utPLSQL-cli/download_file?file_path=utPLSQL-cli-develop-202003131529.zip

Parameter is --coverage-schemes
