### ISSUE TITLE
Where can I find the report file generated in SQL Developer?

### ISSUE THREAD

**Issue by ph88** [utPLSQL/utPLSQL-cli#181]
When I generate coverage.html, I can see it in the Windows \temp directory, but when I try to use exec ut.run ('My object', ut_coverage_sonar_reporter ()); I can't find where the .xml file is generated, help?

Thank you!

**Comment by pesse** [comment]
Hi @ph88 ,
running `exec ut.run()` from SQL Developer or SQL*Plus will not create a file for you. You can instead use utPLSQL-cli to create one:
`utplsql run user/pw@connectstring -p="my_package" -f=ut_coverage_sonar_reporter -o=sonar_coverage.xml`

Does that solve your problem?

**Comment by jgebal** [comment]
@ph88 
When you run utPSLQL from SQLDeveloper worksheet, the outputs will be printed to script console.
You need to have dbms_output enabled.

```
set serverutput on
exec ut.run('My object', ut_coverage_sonar_reporter ());
```
and press `F5` to run as script

What is the need for using `ut_coverage_sonar_reporter ()` from within SQLDeveloper?

**Comment by ph88** [comment]
Thanks for the feedback, in fact I was having trouble generating the ut_coverage_sonar_reporter (.xml) in utPLSQL-cli through Jenkins because afterwards I would need to use the report in the sonar-scannner.

I ended up getting it via utPLSQL-cli after some (several) attempts, it generated the file ut_coverage_sonar_reporter in the folder where utPLSQL-cli is.

Thank you very much.
