### ISSUE TITLE
No Code Coverage Report after Updating to utPLSQL 3.1.10

### ISSUE THREAD

**Issue by DrErique** [utPLSQL/utPLSQL-cli#182]
Hello ! Greetings from Hannover, Germany

We recently updated our utPLSQL Framework to the latest 3.1.10 Version.
Unfortunately Code Coverage Reporting doesn't work anymore after this.

As you might remember we had the #174 Issue where you added the -include Parameter and gave me the https://bintray.com/utplsql/utPLSQL-cli/download_file?file_path=utPLSQL-cli-develop-202003131529.zip Version to try out.

So that worked fine at that time with the 3.1.3 Version and isn't working anymore after update to 3.1.10. There is a file created but has no content.

So we have utplsql-cli Version 3.1.9 and utplsql Version 3.1.10

I tried two different commands :

"utplsql run UNITTEST/Password@WGTEST2 -p=UNITTEST -f=UT_DOCUMENTATION_REPORTER -o=C:\Bamboo_Output\WERTGARANTIE\UNIT_TEST.txt -f=ut_coverage_html_reporter -o=C:\Bamboo_Output\WERTGARANTIE\CODE_COVERAGE.html -include=ISUSER"

and 

"utplsql run UNITTEST/P6YkF-k4il83_0s@WGTEST2 -p=UNITTEST -f=ut_coverage_html_reporter -o=C:\Bamboo_Output\WERTGARANTIE\CODE_COVERAGE_2.html -include=ISUSER"

Unit Testing is running and there is an empty Code Coverage Report.
Can you readjust this Problem ?

**Comment by DrErique** [comment]
Hello Samuel !
Just received some comments from Issue #145 so I see you're still active :-)
Is there a chance we can face this issue here or do you see a chance in the near future ?

Kind regards, Derik Wehrmann

**Comment by pesse** [comment]
I am as active as possible with a lot of other things on my plate and in the midst of a pandemic :)
So, the only change here was update of utPLSQL core to 3.1.10?
Does gathering coverage work when you're using `ut.run()`?

**Comment by DrErique** [comment]
Hello Samuel,
Sorry I just wanted to ask. 
I do it by hand now, so that is indeed not a big problem.
I can gather the code coverage information with 

EXEC UT3PLSQL.UT.RUN( 'UNITTEST', ut_coverage_html_reporter(), a_coverage_schemes => ut_varchar2_list('ISUSER') );

That works.
If I want to do the same again with the utPLSQL-cli out of our Bamboo  CI-Pipeline with 

"utplsql run UNITTEST/P6YkF-k4il83_0s@WGTEST2 -p=UNITTEST -f=ut_coverage_html_reporter -o=C:\Bamboo_Output\WERTGARANTIE\CODE_COVERAGE_2.html -include=ISUSER"

no reporting is created.

But that worked before the 3.1.10  !  So maybe there is only a little counter to be set or something.

Nice weekend, DrErique

**Comment by pesse** [comment]
No need to apologize, I just wanted to explain why I'm rather quiet on the project.

I think you are missing the `--coverage-schemes` parameter in your cli call. Can you try this?

```
utplsql run UNITTEST/P6YkF-k4il83_0s@WGTEST2 \
  -p=UNITTEST \
  -f=ut_coverage_html_reporter -o=C:\Bamboo_Output\WERTGARANTIE\CODE_COVERAGE_2.html \
  -include=ISUSER \
  --coverage-schemes=ISUSER
```

The `include`-parameter has a different meaning and its equivalent for ut.run is `a_include_objects`

**Comment by DrErique** [comment]
Hello Samuel,

I knew the difference between the two parameters but unfortunately there has been a terrible mistake happened by copying or whatever.
So when you take


utplsql run UNITTEST/P6YkF-k4il83_0s@WGTEST2 \

  -p=UNITTEST \

  -f=ut_coverage_html_reporter -o=C:\Bamboo_Output\WERTGARANTIE\CODE_COVERAGE_2.html \

  --coverage-schemes=ISUSER

( without the -include) it works !

My fault, thank you for look over that. Issue can be closed.



Von: Samuel Nitsche <notifications@github.com>
Gesendet: Freitag, 26. Juni 2020 12:03
An: utPLSQL/utPLSQL-cli <utPLSQL-cli@noreply.github.com>
Cc: Wehrmann, Derik <D.Wehrmann@wertgarantie.com>; Author <author@noreply.github.com>
Betreff: Re: [utPLSQL/utPLSQL-cli] No Code Coverage Report after Updating to utPLSQL 3.1.10 (#182)


No need to apologize, I just wanted to explain why I'm rather quiet on the project.

I think you are missing the --coverage-schemes parameter in your cli call. Can you try this?

utplsql run UNITTEST/P6YkF-k4il83_0s@WGTEST2 \

  -p=UNITTEST \

  -f=ut_coverage_html_reporter -o=C:\Bamboo_Output\WERTGARANTIE\CODE_COVERAGE_2.html \

  -include=ISUSER \

  --coverage-schemes=ISUSER

The include-parameter has a different meaning and its equivalent for ut.run is a_include_objects

**Comment by pesse** [comment]
Happy to help - we've all been there 😉
