### ISSUE TITLE
UTPLSQL-Cli Execution of Tests in Command Line Step by Step Procedure

### ISSUE THREAD

**Issue by PriyankaKeer** [utPLSQL/utPLSQL-cli#186]
Hi Team,

We tried understanding the procedure of installing and executing utplsql tests in command line, but we are not much clear about it.
Please share a step by step guide for installing and using utplsql cli. It would be a great help if it is provided. We are in project critical activity and not able to get started with cli . Kindly help!

**Comment by pesse** [comment]
Hi @PriyankaKeer 
to install utPLSQL-cli

- Make sure you have at least Java 8 installed
- Download "utPLSQL-cli.zip" from the latest [release page](https://github.com/utPLSQL/utPLSQL-cli/releases/tag/v3.1.8) 
- Extract the contents to a folder on your machine
- run `./bin/utplsql run user/password@dbConnectString` 

Please note that the cli can not be used to install tests into the database, but just to run them and extract the output.

Best,
Sam

**Comment by PriyankaKeer** [comment]
Hi @pesse 
Thanks..
Able to execute the Tests now

Regards
Priyanka
