### ISSUE TITLE
The order of unit testing

### ISSUE THREAD

**Issue by andriusjediksapiens** [utPLSQL/utPLSQL-cli#207]
Hello, in the moment I am upgrading utplsql unit tests from version 2 to version 3. Sadly, but my tests are dependent on each other and the order of testing is really important. Before I used maven plugin on jenkins to run them (maven could execute them in right order), but for v3 I am using utPLSQL-cli. The problem, that I cannot find the logic behind unit test execution as I've tried to use different suite path order and the order of execution seems random. How can I run test in the right order?

**Comment by simasch** [comment]
Based on the documentation it is:

1. schema name
2. suite path or test package name if --%suitepath was not specified for that package
3. --%test line number in package

How do you start te tests?
