### ISSUE TITLE
Inconsistent version number for 3.1.9

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-cli#216]
All previous utPLSQL-cli releases had version number in releases starting with a letter `v` like `v3.1.8`
Latest release however is missing the `v` letter and therefore is breaking the naming convention.

We need to fix this by making another release of the same sourcecode under tag `v3.1.9` and make sure that next releases are following the same naming conventions.

**Comment by simasch** [comment]
Why do we need that?

The tag is based on the Maven version that doesn't have a prefix.

**Comment by jgebal** [comment]
It was only for consistency and I considered last rekease tagging approach to be changed by mistske.
If we want to fo donerhong let's be consistent. 

What do you suggest?

**Comment by simasch** [comment]
This was not a mistake, the tags are created based on the Maven version, which is done automatically by the GitFlow plugin.

This makes sense, as the Maven version should be the same. In this case, the prefix v in the old tags could be considered inconsistent.

Therefore I'm closing this issue.
