### ISSUE TITLE
Mapping Source Files to DB Objects for Coverage Reporting When Source File Has Multiple Objects.

### ISSUE THREAD

**Issue by Rahman223** [utPLSQL/utPLSQL-cli#218]
Hi, 

I have been struggling with the mapping of our project source files to database objects. The project contains some source files that have multiple database objects defined in the same file. I am able to map source files that have single object per file and coverage for those are shown as expected on sonarqube. However, when mapping the files with multiple objects, coverage is only shown for one of the objects that is mapped and rest are ignored. Is there a way to map these source files that consist of many objects in a explicit manner where every object defined in the file is mapped and reported on?

**Comment by jgebal** [comment]
I'm sorry but no. It is not possible to map ot like that. As dar as I know no framework is supporting this approach.
The simple rule is 1 object = 1 file.
Sonar dies not support this either.
You really need to have 1 object per 1 file fro this fearure to work.
