### ISSUE TITLE
command line options failing

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-cli#29]
I would expect the below command to succeed:
```bash
utPLSQL-cli/bin/utplsql run ${UT3_TESTER}/${UT3_TESTER_PASSWORD}@${CONNECTION_STR} \
-source_path=source -test_path=tests \
-f=ut_documentation_reporter  -c -o=test_results.log -s \
-f=ut_coverage_sonar_reporter -o=coverage.xml \
-f=ut_sonar_test_reporter     -o=test_results.xml
```
It fails however reporting invalid parameter values:
https://travis-ci.org/utPLSQL/utPLSQL/jobs/260426161#L5844

The line that is causing the issues is:
`-f=ut_documentation_reporter  -c -o=test_results.log -s `
it was working fine when I used:
`-f=ut_documentation_reporter  -c `

**Comment by viniciusam** [comment]
I don't treat -c as a sub parameter of -f. I thought it was the default behaviour for the sql-cli too:
```
Parameters -f, -o, -s are correlated. That is parameters -o and -s are controlling outputs for reporter specified by the preceding -f parameter.
```

If you use:
```
-f=ut_documentation_reporter -o=test_results.log -s -c
```
it should work, because -c will be treated as a run parameter, not a -f sub parameter.

**Comment by jgebal** [comment]
So what you are saying is that we cannot put the -c parameter anywhere we like.
That is nothing can go between -f -o -s sequence?
That is a bit restrictive. I'm not saying we must change this but this needs to be explicitly documented.
sql-cli just has a rule: associate the -s and -o to the preceding -f parameter. It does not care if there is some other parameter in between

**Comment by viniciusam** [comment]
Yes, it's a bit restrictive but makes sense to have correlated parameters together. I would like to leave it as is and update the docs.

**Comment by jgebal** [comment]
That solution will work just fine :)
