### ISSUE TITLE
Use TNS for connecting to the db

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-cli#30]
https://stackoverflow.com/questions/19536162/how-to-connect-jdbc-to-tns-oracle

**Comment by jgebal** [comment]
We want to allow `utplsql-cli` to connect to DB using TNS names instaed of forcing them to provide full connect string

**Comment by viniciusam** [comment]
I expect that to be solved on the branch:
https://github.com/utPLSQL/utPLSQL-cli/tree/feature/remove_connection_parser

I changed the client to use the PoolDataSource to get the connections, and now I'm just passing the connection string without any parsing.

**Comment by pesse** [comment]
Fixed via #42
