### ISSUE TITLE
Database sessions remaining open

### ISSUE THREAD

**Issue by viniciusam** [utPLSQL/utPLSQL-cli#35]
Check if Database sessions are correctly closed after an exception occurs.

**Comment by viniciusam** [comment]
I just invalidated the ut_runner package here to reproduce this error, and yes 1 connection remains alive after client exits.

This is because I'm forcing the threads to shutdown when an error occurs.

I create at least two threads on the client, 1 for the tests execution and 1 or more for gathering the reporters output.

RunCommand Line 138:
https://github.com/utPLSQL/utPLSQL-cli/blob/develop/src/main/java/org/utplsql/cli/RunCommand.java#L138

and
RunCommand Line 162:
https://github.com/utPLSQL/utPLSQL-cli/blob/develop/src/main/java/org/utplsql/cli/RunCommand.java#L162

I do that because otherwise, the reports thread would be alive until it reached the execution timeout. I'm not sure how to do that without forcing the thread to shutdown. Actually, I expected the connection to be closed since I'm using try-with-resources.

If it's not clear, we can have a call about it.

**Comment by pesse** [comment]
Closed via https://github.com/utPLSQL/utPLSQL-java-api/pull/25
