### ISSUE TITLE
Add build matrix on Travis with diffrent versions of utPLSQL

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-cli#36]
Client needs to be validated and signed to work with particular versions of `utPLQL` core project.
It would be great to have a build matrix running client against utPLSQL 3.0.0 - 3.0.3 so we always know what version it is compatible with.

**Currently the builds do not give clear indication of version the client is compatible with.**

**Comment by pesse** [comment]
This is done in java-api. All compatibility should reside in java-api, therefore cli is only tested vs latest development branch of both, utPLSQL and java-api.
