### ISSUE TITLE
utPLSQL-cli disconnects while tests are still running

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-cli#38]
If utPLSQL tests are running more than x minutes (20?), we get a timeout on utPLSQL-cli.

https://stackoverflow.com/questions/5913569/how-to-set-query-timeout-on-preparedstatement

I would like this timeout be be much much higher.

**Comment by viniciusam** [comment]
I expect that to be solved on the branch:
https://github.com/utPLSQL/utPLSQL-cli/tree/feature/remove_connection_parser

I changed the client to use the PoolDataSource to get the connections, and it has no timeout.
I tested it with the utPLSQL-cli-test-20170927.zip version, which is built using this branch and it worked.
Would be great if you could test it too.
