### ISSUE TITLE
ORA-20202: Invalid path format: NULL

### ISSUE THREAD

**Issue by vasso123** [utPLSQL/utPLSQL-cli#39]
With a fresh utplsql install on a 11g database, when trying to run tests with utplsql-cli, I get this error:
```
$ ./utplsql run scott/tiger@devdbas:1521/dev.world -c
ORA-20202: Invalid path format: NULL
ORA-06512: at "UT3.UT_RUNNER", line 99
ORA-06512: at line 1

Closed Connection
```

I inspected the problem, and it seems that the a_paths array arrives empty in the ut_runner.run procedure, even though utplsql-cli sends 'scott' in it.

- tested on Ubuntu 16.04
- Oracle Java used:
```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
- Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
- utplsql v3.0.3.1266
- utplsql-cli downloaded from https://bintray.com/viniciusam/utPLSQL-cli/download_file?file_path=utPLSQL-cli-test-20170927.zip
- also tested on a Windows 7 machine
- also tested on another 11g database

**Comment by Prismapanda** [comment]
I had the same problem with an Oracle 11g database. With XE everthing worked fine.

The problem has been be solved by adding the orai18n.jar to the classpath (add it to /lib dir and in utplsql.bat). Maybe it should be added by default? This was really nasty to trace back.

**Comment by vasso123** [comment]
I'll try it tomorrow. How did you figured it out?

**Comment by jgebal** [comment]
[The Oracle Doc - JDBC FAQ mentions](http://www.oracle.com/technetwork/articles/sql/jdbc-faq-090281.html)
>orai18n.jar - Contains the configuration information to support all  Oracle character  sets in Advanced Data Types (objects). **If the database  character set is  one other than UCS2,ASCII, ISO_LATIN_1, UTF8 and  AL32UTF8 and the  application uses ADTs, then you must include this file  in your  classpath.**

utPLSQL-cli communicates wuth utPLSQL using API with ADT's. 

To support different character sets, we would need to include the file in our client bundle.
Expecting users to download it themselves and put it on `classpath` might lead to issues and dissatisfaction.

@viniciusam - any thoughts?

**Comment by viniciusam** [comment]
Yes, we should bundle the library with the client and I'm already working on a PR for that.

**Comment by vasso123** [comment]
Now it works for me also, thanks!
