### ISSUE TITLE
Wrong times in jenkins test result view for run time of tests

### ISSUE THREAD

**Issue by tkleiber** [utPLSQL/utPLSQL-cli#61]
Don't know it this issue fit's here or should be in the utplsql project direct.

See first the console output:

![console](https://user-images.githubusercontent.com/2185441/35722974-6dc8d74c-07f0-11e8-8b6a-9c682444d836.png)

There you see, that the test running 142 seconds.

But the test results view show 4 year and 6 month running, all the other durations are wrong too:

![test_result](https://user-images.githubusercontent.com/2185441/35723034-ab3f8f44-07f0-11e8-8ff9-5fb4887a7292.png)

**Comment by pesse** [comment]
Can you share the command you're running and its parameters?

**Comment by tkleiber** [comment]
I think the problem is that ut_xunit_reporter creates it's output with the date format of the database, which is our case german, and therefore with commas instead of points:

<testsuites tests="532" skipped="6" error="0" failure="1" name="" time="142,204166" >

**Comment by pesse** [comment]
I see. If I remember correctly you need to have the database in German for some of your tests are dependent on that. Otherwise the latest cli (development branch) now reacts to NLS_LANG-environment variable so you could set that to en_US.

@jgebal should we force specific number-format on our reporters? Maybe at least xunit reporter?

**Comment by tkleiber** [comment]
No - my database is by default in German. I have to switch to several other languages to ensure, that some outputs remains in a defined language and some have to change, for an example an English colleague calls a invoice for a Spanish customer. In this case the GUI has to be shown in English but the invoice report furthermore in Spanish.

I don't have Jenkins here in German, only the GUI is german, so cannot test this there.

Does not find, if the junit xml formatter is dependent from environment, maybe this would help?

**Comment by pesse** [comment]
@tkleiber Not sure if I understand your usecase properly. You want

run CI database in German (NLS_SETTINGS-wise) but get en_US number-format for xunit-report?

or

run CI database in en_US (not possible with cli 3.0.4, but with the current development branch)?

**Comment by tkleiber** [comment]
Test objects run in database, where following is set according to nls_database_parameters:
NLS_LANGUAGE 	GERMAN
NLS_TERRITORY	GERMANY

Test sessions has to be run in different nls_session_paramters as described above.

Jenkins run on Linux and seems to require English format in the xunit-reports.

**Comment by jgebal** [comment]
I wonder.
Isn't XML enforcing a standard of "." as separator?
Maybe we should fix it in the reporter.

**Comment by pesse** [comment]
You're right, it is according to w3c XML Schema:
https://www.w3.org/TR/xmlschema-2/#decimal

> decimal has a lexical representation consisting of a finite-length sequence of decimal digits (#x30-#x39) separated by a **period** as a decimal indicator

**Comment by jgebal** [comment]
Submitted new issue to utPLSQL.

**Comment by jgebal** [comment]
@tkleiber - this fix will be part of next release of utPLSQL
