### ISSUE TITLE
Ommit <main class> it command line output with no arguments

### ISSUE THREAD

**Issue by tschf** [utPLSQL/utPLSQL-cli#63]
If I run the batch script with no arguments, I get:

```
C:\Users\trent\utPLSQL-cli\bin>utplsql.bat
Usage: <main class> [command] [command options]
  Commands:
    run      run tests
```

I think the `<main class>` is not an actual part of required input, right?

**Comment by pesse** [comment]
You should be able to call the CLI from a windows command prompt like follows:

`utplsql run yourUser/yourPassword@connectString`

No need to call utplsql.bat.

**Comment by tschf** [comment]
Ah ok, good to know. Still it prints the same. Was just pointing out if the string `<main class>` should be included in the (help) output.

**Comment by jgebal** [comment]
Should show: `utplsql`
