### ISSUE TITLE
Try thick connection first and use thin as fallback (similar approach as SQLcl)

### ISSUE THREAD

**Issue by pesse** [utPLSQL/utPLSQL-cli#91]
This relates to #90 
We should try connecting through thick (`jdbc:oracle:oci8:`) first and use thin (`jdbc:oracle:thin:`) as fallback.

**Comment by SebGt** [comment]
Hello, Do you have an idea of when this will be tried ?

Thanks

**Comment by pesse** [comment]
I can probably poke at it today evening. My concern is that it will introduce more complexity, it will also be hard to test via automated testing.
