### ISSUE TITLE
JDK 8, 9 and 10 compatibility

### ISSUE THREAD

**Issue by pesse** [utPLSQL/utPLSQL-cli#92]
For we are using JAXB in cli, there might be some additional effort needed to ensure compatibility with JDK 8, 9 and 10

**Comment by jgebal** [comment]
Should we add testing on all 3 jdk versions into Travis build matrix?

**Comment by pesse** [comment]
I'm not sure yet. Have to read/experiment around the new things.

**Comment by pesse** [comment]
Main problem at the moment is our usage of `com.sun.nio.zipfs.ZipPath` for HTML Coverage reporter

**Comment by pesse** [comment]
Made several tests with different java-versions installed and didn't find any issues.
We'll need to assure the compatibility with Java 8-12 by automated tests, but I'll create a separate issue for that.
