### ISSUE TITLE
Where is 3.1.1?

### ISSUE THREAD

**Issue by nrogachev** [utPLSQL/utPLSQL-cli#96]
Hi guys,

i remember seeing an email that utPLSQL-cli 3.1.1 is released but it seems to be gone already - by [this link](https://github.com/utPLSQL/utPLSQL-cli/releases/tag/v3.1.1) i get "Page not found".
Was it postponed or something went wrong with the release page?

**Comment by jgebal** [comment]
The release was a bit premature so we held off with it as two minor issues were found.
Sorry for that.

**Comment by nrogachev** [comment]
ah, ok, no problem!
